SET C51INC=F:\c51keilpathwork\C51\Inc;F:\c51keilpathwork\C51\Inc\STC
SET C51LIB=F:\c51keilpathwork\C51\Lib
SET CPU_TYPE=STC15F104W Series
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"F:\c51keilpathwork\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"F:\c51keilpathwork\C51\BIN\C51.EXE" @".\Objects\main.__i"
"F:\c51keilpathwork\C51\BIN\BL51.EXE" @".\Objects\main.lnp"
"F:\c51keilpathwork\C51\BIN\OH51.EXE" ".\Objects\main" 
